[package]
name = "rozsda-ide"
version = "0.0.1"
authors = ["Varga Dániel <varga.daniel@protonmail.com>"]

[dependencies]
gdk = "0.6"
pango = "0.2.0"
tiny-keccak = "1.4.0"

[dependencies.sourceview]
features = ["v3_18"]
version = "0.2"

[dependencies.gtk]
features = ["v3_22"]
version = "0.2"